//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPFramework.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ERPFramework.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationYear.
        /// </summary>
        public static string ApplicationYear {
            get {
                return ResourceManager.GetString("ApplicationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ApplicationYear Short.
        /// </summary>
        public static string ApplicationYearShort {
            get {
                return ResourceManager.GetString("ApplicationYearShort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        public static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Automatic16 {
            get {
                object obj = ResourceManager.GetObject("Automatic16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Automatic16g {
            get {
                object obj = ResourceManager.GetObject("Automatic16g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Calendar16 {
            get {
                object obj = ResourceManager.GetObject("Calendar16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Calendar16g {
            get {
                object obj = ResourceManager.GetObject("Calendar16g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Calendar24 {
            get {
                object obj = ResourceManager.GetObject("Calendar24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Calendar24g {
            get {
                object obj = ResourceManager.GetObject("Calendar24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Checked32 {
            get {
                object obj = ResourceManager.GetObject("Checked32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Checked32g {
            get {
                object obj = ResourceManager.GetObject("Checked32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CircledLeft32 {
            get {
                object obj = ResourceManager.GetObject("CircledLeft32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CircledLeft32g {
            get {
                object obj = ResourceManager.GetObject("CircledLeft32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collate.
        /// </summary>
        public static string Collate {
            get {
                return ResourceManager.GetString("Collate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Collate32 {
            get {
                object obj = ResourceManager.GetObject("Collate32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Collate32g {
            get {
                object obj = ResourceManager.GetObject("Collate32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CollateK32 {
            get {
                object obj = ResourceManager.GetObject("CollateK32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap CollateK32g {
            get {
                object obj = ResourceManager.GetObject("CollateK32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copies.
        /// </summary>
        public static string Copies {
            get {
                return ResourceManager.GetString("Copies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Copy32 {
            get {
                object obj = ResourceManager.GetObject("Copy32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Copy32g {
            get {
                object obj = ResourceManager.GetObject("Copy32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string Custom {
            get {
                return ResourceManager.GetString("Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DataBase is Created Successfully.
        /// </summary>
        public static string Database_Create {
            get {
                return ResourceManager.GetString("Database_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database it doesn&apos;t seem of right type.
        ///Create the tables?.
        /// </summary>
        public static string Database_WrongType {
            get {
                return ResourceManager.GetString("Database_WrongType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong version.
        ///The Current Database version is {0}, while the program version is {1}.
        /// </summary>
        public static string Database_WrongVersion {
            get {
                return ResourceManager.GetString("Database_WrongVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete24 {
            get {
                object obj = ResourceManager.GetObject("Delete24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete24g {
            get {
                object obj = ResourceManager.GetObject("Delete24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete32 {
            get {
                object obj = ResourceManager.GetObject("Delete32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Delete32g {
            get {
                object obj = ResourceManager.GetObject("Delete32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Row.
        /// </summary>
        public static string DeleteRow {
            get {
                return ResourceManager.GetString("DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete setting.
        /// </summary>
        public static string DeleteSetting {
            get {
                return ResourceManager.GetString("DeleteSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Doc_Edit {
            get {
                return ResourceManager.GetString("Doc_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string Doc_New {
            get {
                return ResourceManager.GetString("Doc_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready.
        /// </summary>
        public static string Doc_Ready {
            get {
                return ResourceManager.GetString("Doc_Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go.
        /// </summary>
        public static string Doc_Run {
            get {
                return ResourceManager.GetString("Doc_Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elaborating ....
        /// </summary>
        public static string Doc_Running {
            get {
                return ResourceManager.GetString("Doc_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop.
        /// </summary>
        public static string Doc_Stop {
            get {
                return ResourceManager.GetString("Doc_Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Download32 {
            get {
                object obj = ResourceManager.GetObject("Download32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Download32g {
            get {
                object obj = ResourceManager.GetObject("Download32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 100 %.
        /// </summary>
        public static string E_100Perc {
            get {
                return ResourceManager.GetString("E_100Perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 %.
        /// </summary>
        public static string E_10Perc {
            get {
                return ResourceManager.GetString("E_10Perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200 %.
        /// </summary>
        public static string E_200Perc {
            get {
                return ResourceManager.GetString("E_200Perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 20 %.
        /// </summary>
        public static string E_20Perc {
            get {
                return ResourceManager.GetString("E_20Perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 400 %.
        /// </summary>
        public static string E_400Perc {
            get {
                return ResourceManager.GetString("E_400Perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 40 %.
        /// </summary>
        public static string E_40Perc {
            get {
                return ResourceManager.GetString("E_40Perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 50 %.
        /// </summary>
        public static string E_50Perc {
            get {
                return ResourceManager.GetString("E_50Perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70%.
        /// </summary>
        public static string E_70Perc {
            get {
                return ResourceManager.GetString("E_70Perc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Date.
        /// </summary>
        public static string E_AllDate {
            get {
                return ResourceManager.GetString("E_AllDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Month.
        /// </summary>
        public static string E_CurrentMonth {
            get {
                return ResourceManager.GetString("E_CurrentMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Quarter,.
        /// </summary>
        public static string E_CurrentQuarter {
            get {
                return ResourceManager.GetString("E_CurrentQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Semester.
        /// </summary>
        public static string E_CurrentSemester {
            get {
                return ResourceManager.GetString("E_CurrentSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Trimester.
        /// </summary>
        public static string E_CurrentTrimester {
            get {
                return ResourceManager.GetString("E_CurrentTrimester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CurrentTwo-Month.
        /// </summary>
        public static string E_CurrentTwoMonth {
            get {
                return ResourceManager.GetString("E_CurrentTwoMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Week.
        /// </summary>
        public static string E_CurrentWeek {
            get {
                return ResourceManager.GetString("E_CurrentWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Year.
        /// </summary>
        public static string E_CurrentYear {
            get {
                return ResourceManager.GetString("E_CurrentYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom.
        /// </summary>
        public static string E_Custom {
            get {
                return ResourceManager.GetString("E_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Integer.
        /// </summary>
        public static string E_Integer {
            get {
                return ResourceManager.GetString("E_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Four-Months.
        /// </summary>
        public static string E_LastFourMonths {
            get {
                return ResourceManager.GetString("E_LastFourMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Month.
        /// </summary>
        public static string E_LastMonth {
            get {
                return ResourceManager.GetString("E_LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Nine-Months.
        /// </summary>
        public static string E_LastNineMonths {
            get {
                return ResourceManager.GetString("E_LastNineMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Six-Months.
        /// </summary>
        public static string E_LastSixMonths {
            get {
                return ResourceManager.GetString("E_LastSixMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Three-Months.
        /// </summary>
        public static string E_LastThreeMonths {
            get {
                return ResourceManager.GetString("E_LastThreeMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Two-Months.
        /// </summary>
        public static string E_LastTwoMonths {
            get {
                return ResourceManager.GetString("E_LastTwoMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Week.
        /// </summary>
        public static string E_LastWeek {
            get {
                return ResourceManager.GetString("E_LastWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Year.
        /// </summary>
        public static string E_LastYear {
            get {
                return ResourceManager.GetString("E_LastYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numerico.
        /// </summary>
        public static string E_Numeric {
            get {
                return ResourceManager.GetString("E_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string E_Page_All {
            get {
                return ResourceManager.GetString("E_Page_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        public static string E_Page_Current {
            get {
                return ResourceManager.GetString("E_Page_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Range.
        /// </summary>
        public static string E_Page_Range {
            get {
                return ResourceManager.GetString("E_Page_Range", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Width.
        /// </summary>
        public static string E_Page_Width {
            get {
                return ResourceManager.GetString("E_Page_Width", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Month.
        /// </summary>
        public static string E_PreviousMonth {
            get {
                return ResourceManager.GetString("E_PreviousMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Quarter.
        /// </summary>
        public static string E_PreviousQuarter {
            get {
                return ResourceManager.GetString("E_PreviousQuarter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Semester.
        /// </summary>
        public static string E_PreviousSemester {
            get {
                return ResourceManager.GetString("E_PreviousSemester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Trimester.
        /// </summary>
        public static string E_PreviousTrimester {
            get {
                return ResourceManager.GetString("E_PreviousTrimester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Two-Month.
        /// </summary>
        public static string E_PreviousTwoMonth {
            get {
                return ResourceManager.GetString("E_PreviousTwoMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Week.
        /// </summary>
        public static string E_PreviousWeek {
            get {
                return ResourceManager.GetString("E_PreviousWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Year.
        /// </summary>
        public static string E_PreviousYear {
            get {
                return ResourceManager.GetString("E_PreviousYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string E_Text {
            get {
                return ResourceManager.GetString("E_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole Page.
        /// </summary>
        public static string E_Whole_Page {
            get {
                return ResourceManager.GetString("E_Whole_Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit24 {
            get {
                object obj = ResourceManager.GetObject("Edit24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit24g {
            get {
                object obj = ResourceManager.GetObject("Edit24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit32 {
            get {
                object obj = ResourceManager.GetObject("Edit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Edit32g {
            get {
                object obj = ResourceManager.GetObject("Edit32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string en_US {
            get {
                return ResourceManager.GetString("en_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Envelope format.
        /// </summary>
        public static string Envelope {
            get {
                return ResourceManager.GetString("Envelope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to close form without save data ?.
        /// </summary>
        public static string Exit_Close {
            get {
                return ResourceManager.GetString("Exit_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to undo operation without save data ?.
        /// </summary>
        public static string Exit_Undo {
            get {
                return ResourceManager.GetString("Exit_Undo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit24 {
            get {
                object obj = ResourceManager.GetObject("Exit24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit24g {
            get {
                object obj = ResourceManager.GetObject("Exit24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit32 {
            get {
                object obj = ResourceManager.GetObject("Exit32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Exit32g {
            get {
                object obj = ResourceManager.GetObject("Exit32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Filter24 {
            get {
                object obj = ResourceManager.GetObject("Filter24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Filter24g {
            get {
                object obj = ResourceManager.GetObject("Filter24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Filter32 {
            get {
                object obj = ResourceManager.GetObject("Filter32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Filter32g {
            get {
                object obj = ResourceManager.GetObject("Filter32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Force language.
        /// </summary>
        public static string ForceLanguage {
            get {
                return ResourceManager.GetString("ForceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Form32 {
            get {
                object obj = ResourceManager.GetObject("Form32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Form32ck {
            get {
                object obj = ResourceManager.GetObject("Form32ck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Form32ckg {
            get {
                object obj = ResourceManager.GetObject("Form32ckg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Form32g {
            get {
                object obj = ResourceManager.GetObject("Form32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generic.
        /// </summary>
        public static string Generic {
            get {
                return ResourceManager.GetString("Generic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert Row.
        /// </summary>
        public static string InsertRow {
            get {
                return ResourceManager.GetString("InsertRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italian.
        /// </summary>
        public static string it_IT {
            get {
                return ResourceManager.GetString("it_IT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Label.
        /// </summary>
        public static string Label {
            get {
                return ResourceManager.GetString("Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landscape.
        /// </summary>
        public static string Landscape {
            get {
                return ResourceManager.GetString("Landscape", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Laptop32 {
            get {
                object obj = ResourceManager.GetObject("Laptop32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Laptop32ck {
            get {
                object obj = ResourceManager.GetObject("Laptop32ck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Laptop32ckg {
            get {
                object obj = ResourceManager.GetObject("Laptop32ckg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Laptop32g {
            get {
                object obj = ResourceManager.GetObject("Laptop32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter format.
        /// </summary>
        public static string Letter {
            get {
                return ResourceManager.GetString("Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Link24 {
            get {
                object obj = ResourceManager.GetObject("Link24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Link24g {
            get {
                object obj = ResourceManager.GetObject("Link24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap List32 {
            get {
                object obj = ResourceManager.GetObject("List32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap List32g {
            get {
                object obj = ResourceManager.GetObject("List32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        public static string Localization {
            get {
                return ResourceManager.GetString("Localization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Manual16 {
            get {
                object obj = ResourceManager.GetObject("Manual16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Manual16g {
            get {
                object obj = ResourceManager.GetObject("Manual16g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Message16 {
            get {
                object obj = ResourceManager.GetObject("Message16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Message32 {
            get {
                object obj = ResourceManager.GetObject("Message32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Message32g {
            get {
                object obj = ResourceManager.GetObject("Message32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap More32 {
            get {
                object obj = ResourceManager.GetObject("More32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap More32g {
            get {
                object obj = ResourceManager.GetObject("More32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code not Found.
        /// </summary>
        public static string Msg_CodeNotFound {
            get {
                return ResourceManager.GetString("Msg_CodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Continue anyway ?.
        /// </summary>
        public static string Msg_Continue {
            get {
                return ResourceManager.GetString("Msg_Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete it?.
        /// </summary>
        public static string Msg_Delete {
            get {
                return ResourceManager.GetString("Msg_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document not found .
        /// </summary>
        public static string Msg_DocumentNotFound {
            get {
                return ResourceManager.GetString("Msg_DocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing some data in email settings.
        /// </summary>
        public static string Msg_EmailDataMissing {
            get {
                return ResourceManager.GetString("Msg_EmailDataMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Fiscal Code.
        /// </summary>
        public static string Msg_FiscalCode {
            get {
                return ResourceManager.GetString("Msg_FiscalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code not Found.
        ///Do you want insert ?.
        /// </summary>
        public static string Msg_InsertNewCode {
            get {
                return ResourceManager.GetString("Msg_InsertNewCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lenght of fiscalcode must be 11 or 16 characters..
        /// </summary>
        public static string Msg_LenIncorrect {
            get {
                return ResourceManager.GetString("Msg_LenIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The record is locked by {0} from date {1}.
        /// </summary>
        public static string Msg_Locked {
            get {
                return ResourceManager.GetString("Msg_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mail address is in incorrect format.
        /// </summary>
        public static string Msg_MailIncorrect {
            get {
                return ResourceManager.GetString("Msg_MailIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing code definition.
        /// </summary>
        public static string Msg_MissingCodeDef {
            get {
                return ResourceManager.GetString("Msg_MissingCodeDef", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing counter definition.
        /// </summary>
        public static string Msg_MissingCounter {
            get {
                return ResourceManager.GetString("Msg_MissingCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Record Locked.
        /// </summary>
        public static string Msg_RecordLock {
            get {
                return ResourceManager.GetString("Msg_RecordLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want stop process ?.
        /// </summary>
        public static string Msg_StopBatch {
            get {
                return ResourceManager.GetString("Msg_StopBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect Tax Number.
        /// </summary>
        public static string Msg_TaxNo {
            get {
                return ResourceManager.GetString("Msg_TaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap New24g {
            get {
                object obj = ResourceManager.GetObject("New24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap New32 {
            get {
                object obj = ResourceManager.GetObject("New32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap New32g {
            get {
                object obj = ResourceManager.GetObject("New32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing application name.
        /// </summary>
        public static string NoApplicationName {
            get {
                return ResourceManager.GetString("NoApplicationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing application path.
        /// </summary>
        public static string NoApplicationPath {
            get {
                return ResourceManager.GetString("NoApplicationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numeric.
        /// </summary>
        public static string Numeric {
            get {
                return ResourceManager.GetString("Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Orientation.
        /// </summary>
        public static string Orientation {
            get {
                return ResourceManager.GetString("Orientation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        public static string PageSize {
            get {
                return ResourceManager.GetString("PageSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password and the control password are differents.
        /// </summary>
        public static string Password_Different {
            get {
                return ResourceManager.GetString("Password_Different", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password is wrong.
        /// </summary>
        public static string Password_Error {
            get {
                return ResourceManager.GetString("Password_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The password can&apos;t be blank.
        /// </summary>
        public static string Password_NoBlank {
            get {
                return ResourceManager.GetString("Password_NoBlank", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Play32 {
            get {
                object obj = ResourceManager.GetObject("Play32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Play32g {
            get {
                object obj = ResourceManager.GetObject("Play32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Portrait.
        /// </summary>
        public static string Portrait {
            get {
                return ResourceManager.GetString("Portrait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix.
        /// </summary>
        public static string Prefix {
            get {
                return ResourceManager.GetString("Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prefix+Suffix.
        /// </summary>
        public static string PrefixAndSuffix {
            get {
                return ResourceManager.GetString("PrefixAndSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview24 {
            get {
                object obj = ResourceManager.GetObject("Preview24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview24g {
            get {
                object obj = ResourceManager.GetObject("Preview24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview32 {
            get {
                object obj = ResourceManager.GetObject("Preview32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Preview32g {
            get {
                object obj = ResourceManager.GetObject("Preview32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Print24 {
            get {
                object obj = ResourceManager.GetObject("Print24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Print24g {
            get {
                object obj = ResourceManager.GetObject("Print24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Print32 {
            get {
                object obj = ResourceManager.GetObject("Print32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Print32g {
            get {
                object obj = ResourceManager.GetObject("Print32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer Name.
        /// </summary>
        public static string PrinterName {
            get {
                return ResourceManager.GetString("PrinterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code {0} not found!
        ///Do you want insert it now ?.
        /// </summary>
        public static string Rdr_CodeNotFound {
            get {
                return ResourceManager.GetString("Rdr_CodeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code &apos;{0}&apos; not found.
        /// </summary>
        public static string Rdr_NotFound {
            get {
                return ResourceManager.GetString("Rdr_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save24 {
            get {
                object obj = ResourceManager.GetObject("Save24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save24g {
            get {
                object obj = ResourceManager.GetObject("Save24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save32 {
            get {
                object obj = ResourceManager.GetObject("Save32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Save32g {
            get {
                object obj = ResourceManager.GetObject("Save32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Setting.
        /// </summary>
        public static string SaveSetting {
            get {
                return ResourceManager.GetString("SaveSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search16 {
            get {
                object obj = ResourceManager.GetObject("Search16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search16g {
            get {
                object obj = ResourceManager.GetObject("Search16g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search24 {
            get {
                object obj = ResourceManager.GetObject("Search24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search24g {
            get {
                object obj = ResourceManager.GetObject("Search24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search32 {
            get {
                object obj = ResourceManager.GetObject("Search32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Search32g {
            get {
                object obj = ResourceManager.GetObject("Search32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid setting.
        /// </summary>
        public static string Setting {
            get {
                return ResourceManager.GetString("Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Setting32 {
            get {
                object obj = ResourceManager.GetObject("Setting32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Setting32g {
            get {
                object obj = ResourceManager.GetObject("Setting32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Settings24 {
            get {
                object obj = ResourceManager.GetObject("Settings24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Settings24g {
            get {
                object obj = ResourceManager.GetObject("Settings24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Shutdown32 {
            get {
                object obj = ResourceManager.GetObject("Shutdown32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Shutdown32g {
            get {
                object obj = ResourceManager.GetObject("Shutdown32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SortDown32 {
            get {
                object obj = ResourceManager.GetObject("SortDown32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SortDown32g {
            get {
                object obj = ResourceManager.GetObject("SortDown32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SortLeft32 {
            get {
                object obj = ResourceManager.GetObject("SortLeft32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SortLeft32g {
            get {
                object obj = ResourceManager.GetObject("SortLeft32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SortRight32 {
            get {
                object obj = ResourceManager.GetObject("SortRight32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SortRight32g {
            get {
                object obj = ResourceManager.GetObject("SortRight32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SortUp32 {
            get {
                object obj = ResourceManager.GetObject("SortUp32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SortUp32g {
            get {
                object obj = ResourceManager.GetObject("SortUp32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        public static string Source {
            get {
                return ResourceManager.GetString("Source", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL Compact.
        /// </summary>
        public static string SQLCompact {
            get {
                return ResourceManager.GetString("SQLCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQLite.
        /// </summary>
        public static string SQLite {
            get {
                return ResourceManager.GetString("SQLite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sql Server.
        /// </summary>
        public static string SQLServer {
            get {
                return ResourceManager.GetString("SQLServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Stop32 {
            get {
                object obj = ResourceManager.GetObject("Stop32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Stop32g {
            get {
                object obj = ResourceManager.GetObject("Stop32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suffix.
        /// </summary>
        public static string Suffix {
            get {
                return ResourceManager.GetString("Suffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string T_Email {
            get {
                return ResourceManager.GetString("T_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generics.
        /// </summary>
        public static string T_GlobalPref {
            get {
                return ResourceManager.GetString("T_GlobalPref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  of 4000.
        /// </summary>
        public static string T_OfChar {
            get {
                return ResourceManager.GetString("T_OfChar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer.
        /// </summary>
        public static string T_Printer {
            get {
                return ResourceManager.GetString("T_Printer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thesaurus.
        /// </summary>
        public static string T_Thesaurus {
            get {
                return ResourceManager.GetString("T_Thesaurus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TriangleDown16 {
            get {
                object obj = ResourceManager.GetObject("TriangleDown16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TriangleDown16g {
            get {
                object obj = ResourceManager.GetObject("TriangleDown16g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TriangleLeft16 {
            get {
                object obj = ResourceManager.GetObject("TriangleLeft16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TriangleLeft16g {
            get {
                object obj = ResourceManager.GetObject("TriangleLeft16g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TriangleRight16 {
            get {
                object obj = ResourceManager.GetObject("TriangleRight16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TriangleRight16g {
            get {
                object obj = ResourceManager.GetObject("TriangleRight16g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TriangleUp16 {
            get {
                object obj = ResourceManager.GetObject("TriangleUp16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap TriangleUp16g {
            get {
                object obj = ResourceManager.GetObject("TriangleUp16g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Undo24 {
            get {
                object obj = ResourceManager.GetObject("Undo24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Undo24g {
            get {
                object obj = ResourceManager.GetObject("Undo24g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Undo32 {
            get {
                object obj = ResourceManager.GetObject("Undo32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Undo32g {
            get {
                object obj = ResourceManager.GetObject("Undo32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap User32 {
            get {
                object obj = ResourceManager.GetObject("User32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap User32ck {
            get {
                object obj = ResourceManager.GetObject("User32ck", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap User32ckg {
            get {
                object obj = ResourceManager.GetObject("User32ckg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap User32g {
            get {
                object obj = ResourceManager.GetObject("User32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t delete or modify this file.
        /// </summary>
        public static string Xml_Delete {
            get {
                return ResourceManager.GetString("Xml_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings for login.
        /// </summary>
        public static string Xml_Setting {
            get {
                return ResourceManager.GetString("Xml_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ZoomIn32 {
            get {
                object obj = ResourceManager.GetObject("ZoomIn32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ZoomIn32g {
            get {
                object obj = ResourceManager.GetObject("ZoomIn32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ZoomOut32 {
            get {
                object obj = ResourceManager.GetObject("ZoomOut32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ZoomOut32g {
            get {
                object obj = ResourceManager.GetObject("ZoomOut32g", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
